In [4]:
import cv2

In [6]:
im_g=cv2.imread("smallgray.png",0)
print(im_g)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [8]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [9]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [10]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [14]:
im_g
import numpy

In [15]:
ims=numpy.hstack((im_g,im_g))


In [16]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [17]:
lst=numpy.hsplit(ims,2)

In [18]:
print(lst)

[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]


In [19]:
type(lst)

list

In [20]:
print(lst[0])

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]
